services:
  db:
    container_name: db
    image: "postgres"
    ports:
      - "5430:5432"
    env_file:
      - ./db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moneymap_user -d moneymap"]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    build: ./backend
    container_name: moneymap_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - ./db.env
    environment:
      - USE_DEV_MODE=true
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: moneymap_frontend
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres-data:
