services:
  db:
    container_name: db
    image: "postgres"
    ports:
      - "5430:5432"
    env_file:
      - ./db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moneymap_user -d moneymap"]
      interval: 10s
      retries: 5
      start_period: 10s
    command: ["postgres", "-c", "timezone=Europe/Lisbon"]

  api:
    build: ./backend
    container_name: moneymap_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - ./db.env
    environment:
      - NODE_ENV=development
      - START_SCRIPT=dev
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    command: ["bash", "/app/run.sh"]

  frontend:
    build: ./frontend
    container_name: moneymap_frontend
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

volumes:
  postgres-data:
